name: Fossa

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

jobs:

  scan:
    name: Fossa
    runs-on: ubuntu-20.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Scan
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
